Repository hmcts/wa-task-configuration-api, pull requests merged in 2021-12, with the labels that each got.

#215 RWA-712 Integrate with Fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-215

#217 RWA-1019 [SH] temporarily disabling Fortify from the nightly builds d…
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-217

#218 Rwa 1019
  Jenkinsfile_nightly
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-218
