Repository hmcts/wa-task-configuration-api, pull requests merged in 2021-07, with the labels that each got.

#195 Fix nightly builds failure
  Jenkinsfile_nightly
  security.sh
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-195

#193 RWA-576: Migrate to new role assignment v2 query endpoint, update tests and pact
  charts/wa-task-configuration-api/Chart.yaml
  src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/consumer/roleassignment/RoleAssignmentQueryConsumerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/TaskConfigurationControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/RoleAssignmentServiceApiTest.java
  src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/role/RoleAssignmentService.java
  src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/role/entities/request/MultipleQueryRequest.java
  src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/role/entities/request/QueryRequest.java
  src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/clients/RoleAssignmentServiceApi.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/role/RoleAssignmentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/role/entities/request/MultipleQueryRequestTest.java
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-193

#197 CVE 2021 27568 fix
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-197

#200 Update state on PACT
  src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/consumer/roleassignment/RoleAssignmentQueryConsumerTest.java
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-200

#196 https://tools.hmcts.net/jira/browse/RWA-640
  build.gradle
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-196

#201 Nightly fx
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-201

#199 RWA-585 Update task configuration to include case management category
  README.md
  src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/PostConfigureTaskTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/PostTaskConfigurationTest.java
  src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/camunda/enums/CamundaVariableDefinition.java
  src/main/resources/case_data_with_case_management_category.json
  src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/CamundaServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/CaseConfigurationProviderServiceTest.java
  src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/DmnEvaluationServiceTest.java
  src/testUtils/java/uk/gov/hmcts/reform/wataskconfigurationapi/SpringBootFunctionalBaseTest.java
Labels: ns:wa, prd:wa, rel:wa-task-configuration-api-pr-199
